import { createClient } from 'npm:@supabase/supabase-js@2';

const API = 'https://generativelanguage.googleapis.com/v1beta';
const UPLOAD_API = 'https://generativelanguage.googleapis.com/upload/v1beta/files';
const corsHeaders = {'Access-Control-Allow-Origin':'https://deviahg.lovable.app','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...corsHeaders,'Content-Type':'application/json'}});
function admin(){const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw new Error('Chave secreta do Supabase não disponível.');return createClient(Deno.env.get('SUPABASE_URL')!,key);}
async function authenticate(req:Request){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)throw new Error('Sessão não encontrada.');const a=admin();const {data,error}=await a.auth.getUser(token);if(error||!data.user)throw new Error('Sessão inválida ou expirada.');return {a,user:data.user};}
async function member(a:any,workspaceId:string,userId:string){const {data,error}=await a.from('workspace_members').select('workspace_id').eq('workspace_id',workspaceId).eq('user_id',userId).maybeSingle();if(error)throw new Error('Não foi possível validar o workspace.');if(!data)throw new Error('Você não tem acesso a este workspace.');}
function base64ToBytes(value:string){const binary=atob(value);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
async function uploadToGemini(apiKey:string,bytes:Uint8Array,mimeType:string){const start=await fetch(UPLOAD_API,{method:'POST',headers:{'x-goog-api-key':apiKey,'X-Goog-Upload-Protocol':'resumable','X-Goog-Upload-Command':'start','X-Goog-Upload-Header-Content-Length':String(bytes.byteLength),'X-Goog-Upload-Header-Content-Type':mimeType,'Content-Type':'application/json'},body:JSON.stringify({file:{display_name:'devia-voice.webm'}})});if(!start.ok)throw new Error('Não foi possível iniciar o upload do áudio para o Gemini.');const uploadUrl=start.headers.get('x-goog-upload-url');if(!uploadUrl)throw new Error('O Gemini não devolveu a URL de upload do áudio.');const uploaded=await fetch(uploadUrl,{method:'POST',headers:{'Content-Length':String(bytes.byteLength),'X-Goog-Upload-Offset':'0','X-Goog-Upload-Command':'upload, finalize'},body:bytes});const result=await uploaded.json().catch(()=>({}));if(!uploaded.ok||!result?.file?.uri)throw new Error(result?.error?.message||'O upload do áudio para o Gemini falhou.');return {uri:String(result.file.uri),mimeType:String(result.file.mimeType||mimeType)};}
function extractText(body:any){if(typeof body?.output_text==='string')return body.output_text.trim();const outputs=Array.isArray(body?.outputs)?body.outputs:[];const a=outputs.flatMap((item:any)=>item?.content||[]).map((part:any)=>part?.text||'').join('').trim();if(a)return a;const output=Array.isArray(body?.output)?body.output:[];return output.flatMap((item:any)=>item?.content||[]).map((part:any)=>part?.text||'').join('').trim();}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});try{if(req.method!=='POST')return json({message:'Método não suportado.'},405);const {a,user}=await authenticate(req);const body=await req.json().catch(()=>({}));const workspaceId=String(body.workspaceId||'').trim();const data=String(body.data||'').trim();const mimeType=String(body.mimeType||'audio/webm').trim().split(';')[0];if(!workspaceId)throw new Error('Workspace não encontrado.');await member(a,workspaceId,user.id);if(!data)throw new Error('Áudio vazio.');if(data.length>18000000)throw new Error('Áudio demasiado grande para transcrição.');const supported=new Set(['audio/wav','audio/mp3','audio/aiff','audio/aac','audio/ogg','audio/flac','audio/mpeg','audio/m4a','audio/l16','audio/opus','audio/alaw','audio/mulaw','audio/webm']);if(!supported.has(mimeType))throw new Error('Formato de áudio não suportado: '+mimeType);const apiKey=Deno.env.get('GEMINI_API_KEY');if(!apiKey)throw new Error('GEMINI_API_KEY não configurada.');const file=await uploadToGemini(apiKey,base64ToBytes(data),mimeType);const response=await fetch(API+'/interactions',{method:'POST',headers:{'x-goog-api-key':apiKey,'Content-Type':'application/json'},body:JSON.stringify({model:'gemini-3.5-transcribe',input:[{type:'audio',uri:file.uri,mime_type:file.mimeType}],generation_config:{transcription_config:{mode:'smart',language_codes:[]}}})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result?.error?.message||'O Gemini não conseguiu transcrever o áudio.');const transcript=extractText(result);if(!transcript)throw new Error('O Gemini concluiu sem devolver texto de transcrição.');return json({transcript});}catch(e){return json({message:e instanceof Error?e.message:'ai_transcribe_failed'},400);}});