import { badge, button, icon, pageHeading, escapeHtml } from '../components/ui.js';
import { getActiveProject } from '../services/project-service.js';

function metricCard(label, value, meta, symbol, tone) {
  return `<article class="metric-card"><div class="metric-card__top"><span>${label}</span><span class="metric-icon metric-icon--${tone}">${icon(symbol, 17)}</span></div><strong>${value}</strong><small>${meta}</small></article>`;
}

export function renderDashboard() {
  const project = getActiveProject();
  const actions = `${button('Abrir projeto', { iconName: 'arrow', href: '/preview', variant: 'primary' })}${button('Novo projeto', { iconName: 'plus', action: 'new-project' })}`;
  return `${pageHeading('TERÇA-FEIRA, 06 DE OUTUBRO', 'Seu espaço de criação.', 'Um lugar para transformar ideias em software, com IA no seu fluxo.', actions)}
    <section class="welcome-banner"><div class="welcome-banner__glow"></div><div class="welcome-banner__content"><div class="welcome-banner__label">${icon('sparkle', 15)} UM NOVO JEITO DE CONSTRUIR</div><h2>Do primeiro prompt<br />ao <span>próximo grande projeto.</span></h2><p>Seu workspace DevIA está pronto para começar. Conecte as peças quando fizer sentido para você.</p><a class="banner-link" href="/conversations" data-link>Explorar o workspace ${icon('arrow', 15)}</a></div><div class="welcome-art" aria-hidden="true"><div class="orbit orbit--one"></div><div class="orbit orbit--two"></div><div class="orbit orbit--three"></div><div class="welcome-art__core"><span class="welcome-art__spark">✳</span></div><span class="orbit-node orbit-node--one"></span><span class="orbit-node orbit-node--two"></span><span class="orbit-node orbit-node--three"></span><div class="floating-chip floating-chip--top">${icon('code', 14)} <span>Seu código</span></div><div class="floating-chip floating-chip--bottom">${icon('sparkle', 14)} <span>IA, no seu ritmo</span></div></div></section>
    <div class="section-row"><div><span class="eyebrow">VISÃO GERAL</span><h2>Seu projeto atual</h2></div><a href="/projects" data-link class="text-link">Ver todos os projetos ${icon('arrow', 14)}</a></div>
    <section class="project-overview"><div class="project-overview__main"><div class="project-logo project-logo--${project.color}">${icon('layers', 22)}</div><div class="project-overview__copy"><div class="project-title-row"><h3>${escapeHtml(project.name)}</h3>${badge(project.status, 'green', true)}</div><p>${escapeHtml(project.description)}</p><div class="project-meta"><span>${icon('branch', 14)} ${escapeHtml(project.repository)}</span><i></i><span>${icon('clock', 14)} Atualizado ${escapeHtml(project.updatedAt)}</span></div></div></div><a href="/preview" data-link class="project-arrow" aria-label="Abrir projeto">${icon('arrow', 18)}</a></section>
    <section class="metric-grid">${metricCard('Status do projeto', 'Em andamento', 'Tudo pronto para explorar', 'zap', 'violet')}${metricCard('GitHub', 'Desconectado', 'Conecte um repositório quando quiser', 'github', 'blue')}${metricCard('Supabase', 'Desconectado', 'Seu banco pode esperar', 'database', 'green')}</section>
    <div class="dashboard-bottom"><section class="panel activity-panel"><div class="panel-heading"><div><span class="eyebrow">ATIVIDADE</span><h2>Último trabalho</h2></div>${icon('dots', 18)}</div><div class="activity-item"><span class="activity-icon activity-icon--violet">${icon('sparkle', 17)}</span><div class="activity-item__copy"><strong>Workspace criado</strong><p>O ambiente inicial está pronto para receber seu projeto.</p><small>Hoje, 10:43</small></div><span class="activity-indicator"></span></div><div class="activity-item"><span class="activity-icon activity-icon--blue">${icon('folder', 17)}</span><div class="activity-item__copy"><strong>${escapeHtml(project.name)} aberto</strong><p>Projeto demonstrativo selecionado como contexto atual.</p><small>Hoje, 10:42</small></div></div></section><section class="panel next-panel"><div class="panel-heading"><div><span class="eyebrow">SEU WORKSPACE</span><h2>Pronto para evoluir</h2></div><span class="next-panel__spark">${icon('sparkle', 17)}</span></div><p>A fundação está no lugar. As integrações aparecem aqui quando você decidir dar o próximo passo.</p><div class="next-panel__tags"><span>${icon('github', 14)} GitHub</span><span>${icon('database', 14)} Supabase</span><span>${icon('message', 14)} IA</span></div><a href="/settings" data-link class="text-link">Conhecer configurações ${icon('arrow', 14)}</a></section></div>`;
}
