import { icon } from '../components/ui.js';

export function renderLanding() {
  return '<main class="landing-page">' +
    '<header class="landing-nav"><a class="auth-brand" href="/" data-link><span class="brand-mark" aria-hidden="true">DEV</span><strong>DevIA<span>.</span></strong></a><div class="landing-nav__actions"><a class="button button--ghost" href="/login" data-link>Entrar</a><a class="button button--primary" href="/signup" data-link>Criar conta ' + icon('arrow', 15) + '</a></div></header>' +
    '<section class="landing-hero"><div class="landing-hero__copy"><span class="eyebrow">' + icon('sparkle', 13) + ' DESENVOLVA CONVERSANDO</span><h1>Seu projeto.<br /><span>Sua infraestrutura.</span><br />Sua IA.</h1><p>Um espaço para transformar ideias em software, conectar GitHub e Supabase e construir com inteligência artificial.</p><div class="landing-hero__actions"><a class="button button--primary button--large" href="/signup" data-link>Criar minha conta ' + icon('arrow', 16) + '</a><a class="landing-text-link" href="/login" data-link>Já tenho uma conta</a></div></div><div class="landing-visual" aria-hidden="true"><div class="landing-orbit landing-orbit--one"></div><div class="landing-orbit landing-orbit--two"></div><div class="landing-orbit landing-orbit--three"></div><div class="landing-core"><span>✳</span></div><div class="landing-node landing-node--github">' + icon('github', 18) + '</div><div class="landing-node landing-node--db">' + icon('database', 18) + '</div><div class="landing-node landing-node--ai">' + icon('sparkle', 18) + '</div></div></section>' +
    '<section class="landing-features"><article><span>' + icon('github', 17) + '</span><strong>Seu GitHub</strong><p>Conecte seus repositórios ao workspace.</p></article><article><span>' + icon('database', 17) + '</span><strong>Seu Supabase</strong><p>Mantenha os dados e a infraestrutura do seu projeto.</p></article><article><span>' + icon('sparkle', 17) + '</span><strong>Sua IA</strong><p>Converse com a DevIA para evoluir o software.</p></article></section>' +
    '<footer class="landing-footer"><span>DevIA · fundação inicial</span><span>Construído para crescer.</span></footer>' +
  '</main>';
}