import { createClient } from 'npm:@supabase/supabase-js@2';

const GH='https://api.github.com', VER='2026-03-10', TTL=600;
const POST_CORS={'Access-Control-Allow-Origin':'https://deviahg.lovable.app','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};
const GET_CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, OPTIONS'};
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...POST_CORS,'Content-Type':'application/json'}});
const admin=()=>{const k=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}').default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!k)throw Error('Chave secreta do Supabase não disponível.');return createClient(Deno.env.get('SUPABASE_URL')!,k)};
async function auth(req:Request){const t=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!t)throw Error('Sessão não encontrada.');const a=admin(),{data,error}=await a.auth.getUser(t);if(error||!data.user)throw Error('Sessão inválida ou expirada.');return{a,u:data.user}}
async function member(a:any,w:string,u:string){const{data,error}=await a.from('workspace_members').select('workspace_id').eq('workspace_id',w).eq('user_id',u).maybeSingle();if(error)throw Error('Não foi possível validar o workspace.');if(!data)throw Error('Você não tem acesso a este workspace.')}
async function gh(path:string,t:string){const r=await fetch(GH+path,{headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+t,'X-GitHub-Api-Version':VER}}),b=await r.json().catch(()=>({}));if(!r.ok)throw Error('GitHub respondeu HTTP '+r.status+': '+(b.message||'erro desconhecido'));return b}
async function integration(a:any,w:string){const{data,error}=await a.from('integrations').select('secret_ref,external_project_id,metadata,status').eq('workspace_id',w).eq('provider','github').maybeSingle();if(error)throw Error('Não foi possível carregar a conexão do GitHub.');if(!data||data.status!=='connected'||!data.secret_ref)throw Error('GitHub não está conectado neste workspace.');return data}
async function token(a:any,i:any,w:string){
  const{data,error}=await a.rpc('read_github_oauth_secret',{secret_id:i.secret_ref});
  if(error||!data)throw Error('Não foi possível recuperar a credencial segura do GitHub.');
  let p=JSON.parse(String(data));
  if(!p.accessToken)throw Error('Credencial do GitHub inválida ou expirada.');
  if(p.refreshToken&&p.expiresAt&&Number(p.expiresAt)<=Date.now()+120000){
    const config=JSON.parse(Deno.env.get('GITHUB_APP_CONFIG')||'{}');
    const response=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:String(config.clientId||''),client_secret:String(config.clientSecret||''),grant_type:'refresh_token',refresh_token:String(p.refreshToken)}).toString()});
    const refreshed=await response.json().catch(()=>({}));
    if(!response.ok||refreshed.error||!refreshed.access_token)throw Error('A sessão do GitHub expirou e não pôde ser renovada. Conecte o GitHub novamente.');
    p={...p,accessToken:refreshed.access_token,refreshToken:refreshed.refresh_token||p.refreshToken,expiresAt:Date.now()+Number(refreshed.expires_in||28800)*1000,refreshTokenExpiresAt:refreshed.refresh_token_expires_in?Date.now()+Number(refreshed.refresh_token_expires_in)*1000:p.refreshTokenExpiresAt};
    const saved=await a.rpc('store_github_oauth_secret',{secret_value:JSON.stringify(p),secret_name:'devia_github_'+w+'_'+Date.now()});
    if(saved.error||!saved.data)throw Error('Token renovado, mas não foi possível guardar a nova credencial.');
    await a.from('integrations').update({secret_ref:saved.data,updated_at:new Date().toISOString()}).eq('workspace_id',w).eq('provider','github');
  }
  return p.accessToken
}
const norm=(p:string)=>{const o:string[]=[];for(const x of p.replace(/^\/+/,'').split('/')){if(!x||x==='.')continue;if(x==='..'){o.pop();continue}o.push(x)}return o.join('/')};
function b64(s:string){return btoa(unescape(encodeURIComponent(s))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function ub64(s:string){return decodeURIComponent(escape(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((s.length+3)%4))))}
async function mac(secret:string,s:string){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);return new Uint8Array(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(s)))}
const b64bytes=(b:Uint8Array)=>{let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
async function secret(){const c=JSON.parse(Deno.env.get('GITHUB_APP_CONFIG')||'{}');if(!c.clientSecret)throw Error('Configuração do GitHub App incompleta.');return String(c.clientSecret)}
async function sign(p:any,s:string){const x=b64(JSON.stringify(p));return x+'.'+b64bytes(await mac(s,x))}
async function verify(t:string,s:string){const[a,b]=t.split('.');if(!a||!b)throw Error('Preview inválido.');const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(s),{name:'HMAC',hash:'SHA-256'},false,['verify']);const sig=Uint8Array.from(atob(b.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((b.length+3)%4)),c=>c.charCodeAt(0));if(!await crypto.subtle.verify('HMAC',k,sig,new TextEncoder().encode(a)))throw Error('Preview inválido ou adulterado.');const p=JSON.parse(ub64(a));if(Number(p.exp)<Date.now()/1000)throw Error('Preview expirado.');return p}
async function file(t:string,r:string,ref:string,p:string){const q=norm(p);const b=await gh('/repos/'+r+'/contents/'+q.split('/').map(encodeURIComponent).join('/')+'?ref='+encodeURIComponent(ref),t);if(Array.isArray(b)||b.type!=='file')throw Error('Arquivo de preview não encontrado.');return{bytes:Uint8Array.from(atob(String(b.content||'').replace(/\n/g,'')),c=>c.charCodeAt(0)),path:q}}
function type(p:string){const x=p.toLowerCase();if(x.endsWith('.html'))return'text/html; charset=utf-8';if(x.endsWith('.css'))return'text/css; charset=utf-8';if(/\.(js|mjs|jsx|ts|tsx)$/.test(x))return'text/javascript; charset=utf-8';if(x.endsWith('.svg'))return'image/svg+xml';if(x.endsWith('.png'))return'image/png';if(/\.(jpg|jpeg)$/.test(x))return'image/jpeg';if(x.endsWith('.gif'))return'image/gif';if(x.endsWith('.webp'))return'image/webp';if(x.endsWith('.ico'))return'image/x-icon';if(x.endsWith('.woff2'))return'font/woff2';if(x.endsWith('.woff'))return'font/woff';return'application/octet-stream'}
function resolve(cur:string,v:string){if(/^(data:|blob:|https?:|mailto:|tel:|javascript:|#)/i.test(v))return null;const base=cur.includes('/')?cur.slice(0,cur.lastIndexOf('/')+1):'';return norm(v.startsWith('/')?v:base+v)}
const purl=(tok:string,p:string)=>Deno.env.get('SUPABASE_URL')!+'/functions/v1/github-preview/'+encodeURIComponent(tok)+'/'+norm(p).split('/').map(encodeURIComponent).join('/');
function rewrite(s:string,p:string,tok:string,kind:string){const rw=(v:string)=>{const q=resolve(p,v);return q?purl(tok,q):v};if(kind==='html')return s.replace(/\b(?:src|href|action)=(["'])([^"']+)\1/gi,(f,q,v)=>/^(?:https?:|data:|mailto:|tel:|javascript:|#)/i.test(v)?f:f.replace(v,rw(v)));if(kind==='js')return s.replace(/(\bfrom\s*["']|import\s*["']|import\s*\(\s*["'])([^"']+)(["']\s*\)?)/g,(f,a,v,z)=>{const q=resolve(p,v);return q?a+purl(tok,q)+z:f});if(kind==='css')return s.replace(/url\(\s*["']?([^)"']+)["']?\s*\)/gi,(f,v)=>{const q=resolve(p,v.trim());return q?'url("'+purl(tok,q)+'")':f}).replace(/(@import\s*["'])([^"']+)(["'])/gi,(f,a,v,z)=>{const q=resolve(p,v);return q?a+purl(tok,q)+z:f});return s}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:req.headers.get('Origin')==='null'||!req.headers.get('Origin')?GET_CORS:POST_CORS});try{const u=new URL(req.url),parts=u.pathname.split('/').filter(Boolean),i=parts.indexOf('github-preview'),tok=i>=0?decodeURIComponent(parts[i+1]||''):'';if(req.method==='GET'){if(!tok)return new Response('Preview não encontrado.',{status:404});const p=await verify(tok,await secret()),a=admin(),inte=await integration(a,String(p.workspaceId)),gt=await token(a,inte,String(p.workspaceId)),path=norm(parts.slice(i+2).map(decodeURIComponent).join('/'))||'index.html',f=await file(gt,String(p.repository),String(p.ref),path),ct=type(path),kind=ct.startsWith('text/html')?'html':ct.startsWith('text/javascript')?'js':ct.startsWith('text/css')?'css':'';let body:any=f.bytes;if(kind)body=rewrite(new TextDecoder().decode(f.bytes),path,tok,kind);return new Response(body,{headers:{...GET_CORS,'Content-Type':ct,'Cache-Control':'private, max-age=60','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self' https: data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:; style-src 'self' 'unsafe-inline' https: data:; img-src 'self' https: data: blob:; font-src 'self' https: data:; connect-src https: wss:;"}})}if(req.method!=='POST')return json({message:'Método não suportado.'},405);const{a,u:user}=await auth(req),b=await req.json().catch(()=>({})),w=String(b.workspaceId||'').trim();await member(a,w,user.id);const inte=await integration(a,w),gt=await token(a,inte,w);let repo=String(b.repositoryFullName||'').trim(),ref=String(b.ref||'main').trim()||'main';if(!repo){const iid=String(inte.external_project_id||inte.metadata?.installationId||'');const rs=await gh('/user/installations/'+encodeURIComponent(iid)+'/repositories?per_page=100',gt);repo=rs.repositories?.[0]?.full_name||''}if(!repo)return json({message:'Nenhum repositório está autorizado nesta instalação do GitHub. Abra Gerenciar acesso no GitHub e selecione o repositório.'},409);await file(gt,repo,ref,'index.html');const tok2=await sign({workspaceId:w,userId:user.id,repository:repo,ref,exp:Math.floor(Date.now()/1000)+TTL},await secret());return json({previewUrl:purl(tok2,'index.html'),repository:repo,ref,expiresIn:TTL})}catch(e){const m=e instanceof Error?e.message:'github_preview_failed';return req.method==='GET'?new Response(m.slice(0,500),{status:400,headers:{...CORS,'Content-Type':'text/plain'}}):json({message:m.slice(0,500)},400)}});